const express=require('express');
const fs=require('fs');
const path=require('path');
const app=express();
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true}));
const DATA=path.join('/tmp','oilaviy-survey-responses.json');
function read(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return []}}
function write(x){fs.writeFileSync(DATA,JSON.stringify(x,null,2))}
const questions=[["Sizningcha, oila qurish uchun shaxsiy tayyorgarlik zarurmi?",["Ha","Yo‘q","Qisman"]],["Oila qurish uchun eng maqbul yosh oralig‘i qaysi?",["18–22","22–25","25–30","30 yoshdan yuqori"]],["Siz o‘zingizni oilaviy hayotga qanchalik tayyor deb hisoblaysiz?",["To‘liq tayyorman","Qisman tayyorman","Tayyor emasman"]],["Oilada moddiy barqarorlik qanchalik muhim?",["Juda muhim","Muhim","Unchalik muhim emas"]],["Turmush o‘rtoq tanlashda eng muhim fazilat qaysi?",["Halollik","Mehribonlik","Mas’uliyatlilik","Tushunish"]],["Oilaviy hayotda muhabbat asosiy omil deb hisoblaysizmi?",["Ha","Yo‘q","Faqat muhabbat yetarli emas"]],["Oilada er-xotin vazifalari teng bo‘lishi kerakmi?",["Ha","Yo‘q","Vaziyatga qarab"]],["Kelishmovchiliklarni qanday hal qilish kerak?",["Suhbat orqali","Kattalar aralashuvi bilan","Vaqt o‘tishi bilan"]],["Ota-onalar maslahatlari oila qurishda qanchalik muhim?",["Juda muhim","Qisman muhim","Muhim emas"]],["Oilaviy byudjetni rejalashtirishni bilasizmi?",["Ha","Yo‘q","Qisman"]],["Oilaviy hayotga psixologik tayyorgarlik kerakmi?",["Ha","Yo‘q"]],["Farzand tarbiyasiga tayyorgarlikni qachondan boshlash kerak?",["Oila qurishdan oldin","Oila qurgandan keyin","Farzand tug‘ilgach"]],["Ajralishlarning asosiy sababi nimada deb o‘ylaysiz?",["Moddiy muammo","Tushunmovchilik","Ishonchsizlik","Boshqa"]],["Oila qurishda ta’lim darajasi muhimmi?",["Ha","Yo‘q","Qisman"]],["Oilaviy hayotga tayyorgarlik bo‘yicha maxsus kurslar kerakmi?",["Ha","Yo‘q"]],["Ijtimoiy tarmoqlar oilaviy munosabatlarga qanday ta’sir ko‘rsatadi?",["Ijobiy","Salbiy","Har ikkala"]],["Oilada sabr-toqatning o‘rni qanday?",["Juda muhim","Muhim","Unchalik muhim emas"]],["Sizningcha, mustahkam oila qurish uchun eng zarur omil nima?",["Ishonch","Hurmat","Muhabbat","Mas’uliyat"]],["Oilaviy masalalarda mustaqil qaror qabul qilish muhimmi?",["Ha","Yo‘q","Qisman"]],["Siz kelajakda qanday oila qurishni xohlaysiz?",["An’anaviy","Zamonaviy","Aralash (an’anaviy va zamonaviy uyg‘unligi)"]]];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
app.get('/',(req,res)=>{
 const items=questions.map((q,i)=>`<section class="q"><div class="n">${i+1}</div><h3>${esc(q[0])}</h3>${q[1].map(o=>`<label><input type="radio" name="q${i+1}" value="${esc(o)}" required><span>${esc(o)}</span></label>`).join('')}</section>`).join('');
 res.send(`<!doctype html><html lang="uz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SO‘ROVNOMA</title><style>*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f4f7fb;color:#172033}.wrap{max-width:760px;margin:auto;padding:16px}.hero{background:#fff;border-radius:20px;padding:22px;margin:8px 0 16px;box-shadow:0 10px 30px #15223a12}.hero h1{font-size:24px;margin:0 0 8px}.hero p{margin:0;color:#657086}.q{position:relative;background:#fff;border-radius:18px;padding:18px;margin:12px 0;box-shadow:0 8px 24px #15223a0d}.q h3{font-size:17px;line-height:1.4;margin:0 0 14px;padding-left:34px}.n{position:absolute;top:18px;left:18px;width:24px;height:24px;border-radius:8px;background:#2563eb;color:white;display:grid;place-items:center;font-weight:700;font-size:13px}.q label{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid #e4e9f2;border-radius:12px;margin:8px 0;cursor:pointer}.q input{width:20px;height:20px;accent-color:#2563eb}.q label:has(input:checked){border-color:#2563eb;background:#eff6ff}button{width:100%;border:0;border-radius:14px;padding:15px;background:#2563eb;color:white;font-size:17px;font-weight:700;margin:8px 0 30px}.ok{background:#ecfdf3;border:1px solid #bbf7d0;color:#166534;border-radius:16px;padding:20px;text-align:center}small{color:#778196}</style></head><body><div class="wrap"><div class="hero"><h1>SO‘ROVNOMA</h1><p>Oilaviy turmushga tayyorgarlik bo‘yicha so‘rovnoma. Har bir savolga bitta javob belgilang.</p></div><form id="f">${items}<button type="submit">Javoblarni yuborish</button></form><div id="done" hidden class="ok"><b>Rahmat! ✅</b><br>Javoblaringiz qabul qilindi.</div></div><script>const f=document.getElementById('f');f.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(f);const answers={};for(let i=1;i<=20;i++)answers['q'+i]=fd.get('q'+i);const b=f.querySelector('button');b.disabled=true;b.textContent='Yuborilmoqda...';try{const r=await fetch('/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});if(!r.ok)throw 0;f.hidden=true;document.getElementById('done').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}catch{b.disabled=false;b.textContent='Qayta yuborish';alert('Xatolik. Qayta urinib ko‘ring.')}})</script></body></html>`);
});
app.post('/submit',(req,res)=>{
 const a=req.body&&req.body.answers||{};
 for(let i=1;i<=20;i++){if(!a['q'+i])return res.status(400).json({ok:false})}
 const rows=read();rows.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),answers:a});write(rows);res.json({ok:true});
});
app.get('/admin/export.csv',(req,res)=>{
 const rows=read();const head=['createdAt',...questions.map((_,i)=>'S'+(i+1))];
 const csv=[head,...rows.map(r=>[r.createdAt,...questions.map((_,i)=>r.answers['q'+(i+1)]||'')])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');
 res.type('text/csv').set('Content-Disposition','attachment; filename="sorovnoma-javoblari.csv"').send('\ufeff'+csv)
});
app.get('/health',(req,res)=>res.json({ok:true,count:read().length}));
const port=process.env.PORT||10000;app.listen(port,'0.0.0.0',()=>console.log('survey running',port));